# Lab 2-perform lndexing,Slicing and Broadcating in numpy

# program 1 -indexing in numpy

In [9]:
import numpy as np
arr1=np.arange(4)
print("array arr 11:",arr1)
print(" Element at index 0 0f arri is:",arr1[0])
print(" Element at index 1 0f arr1 is:",arr1[1])


array arr 11: [0 1 2 3]
 Element at index 0 0f arri is: 0
 Element at index 1 0f arr1 is: 1


# lndexing in 2 Dimentions

In [11]:
import numpy as np
arr1=np.arange(12)
arr1=arr1.reshape(3,4)
print("array arr1:\n",arr1)
print(" Element at index 0 0f arri is:",arr1[0])
print(" Element at index 1 0f arr1 is:",arr1[1])


array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 Element at index 0 0f arri is: [0 1 2 3]
 Element at index 1 0f arr1 is: [4 5 6 7]


# lndexing in 3 Dimetion

In [13]:
arr1=np.arange(12)
arr1=arr1.reshape(2,2,3)
print("array arr1:\n",arr1)
print("Element:",arr1[1,1,2])


array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element: 11


# program 2-Slicing an array

# slicling 1D Numpy Array

In [15]:
arr=np.arange (6)
print("array arr:",arr)
print(arr[1:5])

array arr: [0 1 2 3 4 5]
[1 2 3 4]


# slicling 2D Numpy Array

In [18]:
arr=np.arange (12)
arr=arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("\n")
print("Element at 1st row and 1st colum upto last colum\n:",arr1[1:,1:4])


Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


Element at 1st row and 1st colum upto last colum
: [[[ 9 10 11]]]


In [20]:
arr=np.arange(1,10)
arr1=arr.reshape(3,3)

# program 3-Numpy Bordcating

In [ ]:
import numpy as np
#creste a 3*3 array
arr=np.array([[1,2,3],
              [4,5,6]
              [7,8,9]])
scalar=10
result=arr+scslar
